#!/usr/bin/bash

alias c='clear'
alias rm='safe-rm'
alias ls='ls -Fh --color=tty'
alias vi='nvim'
alias r='R'
alias open='xdg-open'
alias clip='xclip -selection "clipboard"'
alias phone='scrcpy -Sw &'

# directory shortcuts
alias dots='cd $DOTFILES'
