#!/usr/bin/bash

alias c='clear'
alias rm='safe-rm'
alias ls='ls -Fh --color=tty'
alias vi='nvim'
alias r='R'
alias rg='ranger'
alias t='todo.sh -d $DOTFILES/scripts/todo.txt/todo.cfg'
alias open='xdg-open'
alias clip='xclip -selection "clipboard"'
alias phone='scrcpy -Sw &'
alias gvim='nvim-qt'

alias godot='$HOME/Godot/Godot_v3.3-stable_mono_x11.64'

# directory shortcuts
alias dots='cd $DOTFILES'
